name: Build
on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

jobs:
  build-vsphere-csi:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

    - name: Set the TAG value
      run: |
        TAG=$(make -s log | grep '^TAG=' | cut -d '=' -f2)
        BUILD_META=$(make -s log | grep '^BUILD_META=' | cut -d '=' -f2)
        echo "TAG=${TAG}${BUILD_META}" >> "$GITHUB_ENV"

    - name: Build hardened-vsphere-csi-driver image
      run: make build-image-vsphere-csi

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
      with:
        image-ref: ghcr.io/rancher/hardened-vsphere-csi-driver:${{ env.TAG }}
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        format: 'table'
        exit-code: '0'

  build-syncer:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

    - name: Set the TAG value
      run: |
        TAG=$(make -s log | grep '^TAG=' | cut -d '=' -f2)
        BUILD_META=$(make -s log | grep '^BUILD_META=' | cut -d '=' -f2)
        echo "TAG=${TAG}${BUILD_META}" >> "$GITHUB_ENV"

    - name: Build hardened-vsphere-csi-syncer image
      run: make build-image-syncer

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
      with:
        image-ref: ghcr.io/rancher/hardened-vsphere-csi-syncer:${{ env.TAG }}
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        format: 'table'
        exit-code: '0'

